# Test for try statement
try:
	a = len(1)
except TypeError:
	print("Type error!")
finally:
	print("Finally")

